name: Build electron assets

on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          include:
            - os: ubuntu-latest
              arch: 386
              build: buildWindows386
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup Go environment
          uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            
        - name: Setup MinGW-w64 for 32-bit
          run: |
            sudo apt-get update
            sudo apt-get install -y gcc-mingw-w64
            sudo apt-get install -y gcc-mingw-w64-i686
  
        - name: Check Go version
          run: go version
  
        - name: Setup and build on Windows ${{ matrix.arch }}
          run: |
            sudo bash ./bootstrap_install_mage.sh
            sudo mage ${{ matrix.build }}
  
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: windows-${{ matrix.arch }}-assets
            path: shared/windows/
  
