name: Build electron assets

on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          include:
            - os: windows-latest
              arch: 386
              build: buildWindows386
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup Go environment
          uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            architecture: '386'
            
        - name: Setup MinGW-w64 for 32-bit
          uses: huhu0823/setup-mingw@v2
          with:
            platform: x86

        - name: Check Go version
          run: go version
  
        - name: Setup and build on Windows ${{ matrix.arch }}
          if: runner.os == 'Windows'
          run: |
            echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
            ./bootstrap_install_mage.bat
            mage ${{ matrix.build }}
  
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.os }}-${{ matrix.arch }}-assets
            path: shared/${{ (matrix.os == 'macos-latest' && 'ios' || (matrix.os == 'windows-latest' && 'windows' || 'linux')) }}/
  
