name: Build dll

on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          include:
            - os: windows-2019
              arch: 386
              build: buildWindowsA
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup Go environment
          uses: actions/setup-go@v5
          with:
            go-version: '1.21'
            
        - name: Check Go version
          run: go version
          
        - name: Install Go Mage
          run: go install github.com/magefile/mage@latest

        - uses: egor-tensin/setup-mingw@v2.2.0
          with:
            version: 12.2.0
            platform: x86
  
        - name: Setup and build on Windows ${{ matrix.arch }}
          run: |
            mage ${{ matrix.build }}
  
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: windows-${{ matrix.arch }}-assets
            path: shared/windows/
  
